# Generated by Django 5.0 on 2023-12-17 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account_type',
            fields=[
                ('p_k', models.AutoField(primary_key=True, serialize=False)),
                ('account_type', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('p_k', models.AutoField(primary_key=True, serialize=False)),
                ('Asset_Name', models.TextField(blank=True, null=True)),
                ('Total_Assets', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Liability',
            fields=[
                ('p_k', models.AutoField(primary_key=True, serialize=False)),
                ('Liability_Name', models.TextField(blank=True, null=True)),
                ('Total_Liability', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trial_Balance',
            fields=[
                ('p_k', models.AutoField(primary_key=True, serialize=False)),
                ('Trial_Balance_Name', models.TextField(blank=True, null=True)),
                ('Debit', models.TextField(blank=True, null=True)),
                ('Credit', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cash_Flow',
            fields=[
                ('p_k', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateTimeField(auto_now_add=True, null=True)),
                ('Description', models.CharField(blank=True, max_length=1000, null=True)),
                ('Payment_Method', models.IntegerField(choices=[(0, 'None'), (1, 'Cash'), (2, 'Check'), (3, 'Bank-Card'), (4, 'Bkash'), (5, 'Nagad'), (6, 'Upay')], default=0)),
                ('Payment_Details', models.CharField(blank=True, max_length=1000, null=True)),
                ('Debit', models.TextField(blank=True, null=True)),
                ('Credit', models.TextField(blank=True, null=True)),
                ('Account_Balance', models.TextField(blank=True, null=True)),
                ('Total_Balance', models.TextField(blank=True, null=True)),
                ('Account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment_account.account_type')),
            ],
        ),
        migrations.CreateModel(
            name='List_Account',
            fields=[
                ('p_k', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(blank=True, max_length=1000, null=True)),
                ('Account_Number', models.TextField(blank=True, null=True)),
                ('Note', models.CharField(blank=True, max_length=1000, null=True)),
                ('Balance', models.TextField(blank=True, null=True)),
                ('Account_Details', models.TextField(blank=True, null=True)),
                ('Added_By', models.CharField(blank=True, max_length=1000, null=True)),
                ('Action', models.IntegerField(choices=[(0, 'Action'), (1, 'View'), (2, 'Edit'), (3, 'Delete')], default=0)),
                ('Account_Type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment_account.account_type')),
            ],
        ),
        migrations.CreateModel(
            name='Payment_Account_Report',
            fields=[
                ('p_k', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateTimeField(auto_now_add=True, null=True)),
                ('Payment_Reference_No', models.CharField(blank=True, max_length=1000, null=True)),
                ('Invoice_Or_Reference_No', models.CharField(blank=True, max_length=1000, null=True)),
                ('Amount', models.TextField(blank=True, null=True)),
                ('Payment_Type', models.CharField(blank=True, max_length=1000, null=True)),
                ('Description', models.CharField(blank=True, max_length=1000, null=True)),
                ('Action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment_account.account_type')),
            ],
        ),
    ]
