# Generated by Django 5.0 on 2023-12-25 19:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('smss', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prefix', models.CharField(blank=True, max_length=1000, null=True)),
                ('First_Name', models.CharField(blank=True, max_length=1000, null=True)),
                ('Last_Name', models.CharField(blank=True, max_length=1000, null=True)),
                ('Email', models.CharField(blank=True, max_length=1000, null=True, unique=True)),
                ('Contact_Number', models.CharField(blank=True, max_length=1000, null=True, unique=True)),
                ('Address', models.CharField(blank=True, max_length=1000, null=True)),
                ('Sales_Commission_Percentage', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sales_Commission_Ager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=1000, null=True)),
                ('Email', models.CharField(blank=True, max_length=1000, null=True, unique=True)),
                ('Contact_Number', models.CharField(blank=True, max_length=1000, null=True, unique=True)),
                ('Address', models.CharField(blank=True, max_length=1000, null=True)),
                ('Sales_Commission_Percentage', models.CharField(blank=True, max_length=1000, null=True)),
                ('Action', models.CharField(choices=[('Select', 'Select'), ('View', 'View'), ('Edit', 'Edit'), ('Delete', 'Delete')], default='Select', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Role', models.CharField(blank=True, max_length=1000, null=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='customuser_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='customuser_set', to='auth.permission')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('is_staff', models.BooleanField(blank=True, default=False, null=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('mobile_number', models.CharField(max_length=20, null=True, unique=True)),
                ('position', models.CharField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('Sales_Commission_Percentage', models.CharField(blank=True, max_length=1000, null=True)),
                ('Max_Sales_Discount_Percentage', models.CharField(blank=True, max_length=1000, null=True)),
                ('Date_Of_Birth', models.CharField(blank=True, max_length=1000, null=True)),
                ('Gender', models.CharField(choices=[('Please Select', 'Please Select'), ('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='Please Select', max_length=1000)),
                ('Marital_Status', models.CharField(choices=[('Marital Status', 'Marital Status'), ('Married', 'Married'), ('Unmarried', 'Unmarried'), ('Divorce', 'Divorce')], default='Marital Status', max_length=1000)),
                ('Blood_Group', models.CharField(blank=True, max_length=1000, null=True)),
                ('Phone_Number', models.CharField(blank=True, max_length=1000, null=True)),
                ('Alternate_Contact_Number', models.CharField(blank=True, max_length=1000, null=True)),
                ('Family_Contact_Number', models.CharField(blank=True, max_length=1000, null=True)),
                ('Facebook_Link', models.CharField(blank=True, max_length=1000, null=True)),
                ('Twitter_Link', models.CharField(blank=True, max_length=1000, null=True)),
                ('Permanent_Address', models.CharField(blank=True, max_length=1000, null=True)),
                ('Current_Address', models.CharField(blank=True, max_length=1000, null=True)),
                ('Account_Holders_Name', models.CharField(blank=True, max_length=1000, null=True)),
                ('Account_Number', models.CharField(blank=True, max_length=1000, null=True)),
                ('Bank_Name', models.CharField(blank=True, max_length=1000, null=True)),
                ('Bank_Identifier_Code', models.CharField(blank=True, max_length=1000, null=True)),
                ('Branch', models.CharField(blank=True, max_length=1000, null=True)),
                ('Tax_Payer_ID', models.CharField(blank=True, max_length=1000, null=True)),
                ('Basic_Salary', models.TextField(blank=True, null=True)),
                ('Pay_Term', models.CharField(choices=[('Select', 'Select'), ('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Half of Month', 'Half of Month'), ('Monthly', 'Monthly'), ('Half of Year', 'Half of Year'), ('Yearly', 'Yearly')], default='Select', max_length=1000)),
                ('Pay_Components', models.CharField(blank=True, max_length=1000, null=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smss.all_number')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('Role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_management.roles')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
