# Generated by Django 5.0 on 2023-12-17 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock_Transfer',
            fields=[
                ('p_k', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateTimeField(auto_now_add=True, null=True)),
                ('Reference_No', models.CharField(blank=True, max_length=1000, null=True)),
                ('Location_From', models.CharField(blank=True, max_length=1000, null=True)),
                ('Location_To', models.CharField(blank=True, max_length=1000, null=True)),
                ('Status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Completed'), (2, 'In Transit')], default=0)),
                ('Shipping_Charges', models.TextField(blank=True, null=True)),
                ('Total_Amount', models.TextField(blank=True, null=True)),
                ('Additional_Notes', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
