# Generated by Django 5.0 on 2023-12-25 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contact', '0001_initial'),
        ('payment_account', '0001_initial'),
        ('sell', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Additional_Expense',
            fields=[
                ('p_k', models.AutoField(primary_key=True, serialize=False)),
                ('Expense_Name', models.CharField(blank=True, max_length=1000, null=True)),
                ('Amount', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Add_Purchase',
            fields=[
                ('p_k', models.AutoField(primary_key=True, serialize=False)),
                ('Reference_No', models.CharField(blank=True, max_length=1000, null=True)),
                ('Purchase_Date', models.DateTimeField(auto_now_add=True)),
                ('Purchase_Status', models.CharField(choices=[('Due', 'Due'), ('Recieved', 'Recieved')], default='Due', max_length=1000)),
                ('Address', models.CharField(blank=True, max_length=1000, null=True)),
                ('Pay_Term', models.CharField(choices=[('Select', 'Select'), ('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Half of Month', 'Half of Month'), ('Monthly', 'Monthly'), ('Half of Year', 'Half of Year'), ('Yearly', 'Yearly')], default='Select', max_length=1000)),
                ('Attached_Document', models.FileField(upload_to='Files/')),
                ('Discount_Type', models.CharField(blank=True, max_length=1000, null=True)),
                ('Discount_Amount', models.TextField(blank=True, null=True)),
                ('Purchase_Tax', models.TextField(blank=True, null=True)),
                ('Additional_Notes', models.TextField(blank=True, null=True)),
                ('Shipping_Details', models.CharField(blank=True, max_length=1000, null=True)),
                ('Additional_Shipping_Charges', models.TextField(blank=True, null=True)),
                ('Amount', models.TextField(blank=True, null=True)),
                ('Paid_On', models.DateTimeField(auto_now_add=True)),
                ('Payment_Method', models.CharField(choices=[('None', 'None'), ('Cash', 'Cash'), ('Check', 'Check'), ('Bank-Card', 'Bank-Card'), ('Bkash', 'Bkash'), ('Nagad', 'Nagad'), ('Upay', 'Upay')], default='None', max_length=1000)),
                ('Payment_Note', models.TextField(blank=True, null=True)),
                ('Business_Location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sell.location_set')),
                ('Payment_Account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment_account.account_type')),
                ('Supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contact.business_name')),
                ('Addition_expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase.additional_expense')),
            ],
        ),
        migrations.CreateModel(
            name='List_Purchase_Return',
            fields=[
                ('p_k', models.AutoField(primary_key=True, serialize=False)),
                ('Created_At', models.DateTimeField(auto_now_add=True)),
                ('Reference_No', models.CharField(blank=True, max_length=1000, null=True)),
                ('Parent_Purchase', models.TextField(blank=True, null=True)),
                ('Payment_Status', models.CharField(choices=[('Due', 'Due'), ('Partial', 'Partial'), ('Paid', 'Paid')], default='Due', max_length=1000)),
                ('Grand_Total', models.TextField(blank=True, null=True)),
                ('Payment_Due', models.TextField(blank=True, null=True)),
                ('Location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sell.location_set')),
                ('Supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contact.business_name')),
            ],
        ),
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('p_k', models.AutoField(primary_key=True, serialize=False)),
                ('Created_At', models.DateTimeField(auto_now_add=True)),
                ('Reference_No', models.CharField(blank=True, max_length=1000, null=True)),
                ('Purchase_Status', models.CharField(choices=[('Due', 'Due'), ('Recieved', 'Recieved')], default='Due', max_length=1000)),
                ('Payment_Status', models.CharField(choices=[('Due', 'Due'), ('Partial', 'Partial'), ('Paid', 'Paid')], default='Due', max_length=1000)),
                ('Grand_Total', models.TextField(blank=True, null=True)),
                ('Payment_Due', models.TextField(blank=True, null=True)),
                ('Added_By', models.CharField(blank=True, max_length=1000, null=True)),
                ('Location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sell.location_set')),
                ('Supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contact.business_name')),
            ],
        ),
    ]
