# Generated by Django 5.0 on 2023-12-17 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contact', '0001_initial'),
        ('sell', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Purchase',
            fields=[
                ('p_k', models.AutoField(primary_key=True, serialize=False)),
                ('Reference_No', models.CharField(blank=True, max_length=1000, null=True)),
                ('Purchase_Date', models.DateTimeField(auto_now_add=True)),
                ('Purchase_Status', models.IntegerField(choices=[(0, 'Due'), (1, 'Recieved')], default=0)),
                ('Address', models.CharField(blank=True, max_length=1000, null=True)),
                ('Pay_Term', models.IntegerField(choices=[(0, 'Select'), (1, 'Daily'), (2, 'Weekly'), (3, 'Half of Month'), (4, 'Monthly'), (5, 'Half of Year'), (6, 'Yearly')], default=0)),
                ('Attached_Document', models.FileField(upload_to='Files/')),
                ('Business_Location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sell.location_set')),
                ('Supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contact.business_name')),
            ],
        ),
        migrations.CreateModel(
            name='List_Purchase_Return',
            fields=[
                ('p_k', models.AutoField(primary_key=True, serialize=False)),
                ('Created_At', models.DateTimeField(auto_now_add=True)),
                ('Reference_No', models.CharField(blank=True, max_length=1000, null=True)),
                ('Parent_Purchase', models.TextField(blank=True, null=True)),
                ('Payment_Status', models.IntegerField(choices=[(0, 'Due'), (1, 'Partial'), (2, 'Paid')], default=0)),
                ('Grand_Total', models.TextField(blank=True, null=True)),
                ('Payment_Due', models.TextField(blank=True, null=True)),
                ('Location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sell.location_set')),
                ('Supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contact.business_name')),
            ],
        ),
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('p_k', models.AutoField(primary_key=True, serialize=False)),
                ('Created_At', models.DateTimeField(auto_now_add=True)),
                ('Reference_No', models.CharField(blank=True, max_length=1000, null=True)),
                ('Purchase_Status', models.IntegerField(choices=[(0, 'Due'), (1, 'Recieved')], default=0)),
                ('Payment_Status', models.IntegerField(choices=[(0, 'Due'), (1, 'Partial'), (2, 'Paid')], default=0)),
                ('Grand_Total', models.TextField(blank=True, null=True)),
                ('Payment_Due', models.TextField(blank=True, null=True)),
                ('Added_By', models.CharField(blank=True, max_length=1000, null=True)),
                ('Location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sell.location_set')),
                ('Supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contact.business_name')),
            ],
        ),
    ]
