# Generated by Django 5.0 on 2023-12-17 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Actions', models.IntegerField(choices=[(0, 'Action'), (1, 'Pay'), (3, 'View'), (4, 'Edit'), (5, 'Delete'), (6, 'Deactivate'), (7, 'Ledger'), (8, 'Purchase'), (9, 'Stock Report'), (10, 'Documents & Note')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Business_name',
            fields=[
                ('p_k', models.AutoField(primary_key=True, serialize=False)),
                ('Business_Name', models.CharField(blank=True, max_length=1000, null=True)),
                ('Category', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact_id',
            fields=[
                ('p_k', models.AutoField(primary_key=True, serialize=False)),
                ('Contact_Ids', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Group',
            fields=[
                ('p_k', models.AutoField(primary_key=True, serialize=False)),
                ('Customer_Group_Name', models.CharField(blank=True, max_length=1000, null=True)),
                ('Calculation_Percentage', models.CharField(blank=True, max_length=1000, null=True)),
                ('Selling_Price_Group', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('p_k', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(blank=True, max_length=1000, null=True)),
                ('Email', models.EmailField(blank=True, max_length=1000, null=True, unique=True)),
                ('Mobile', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('Delivery_Address', models.CharField(blank=True, max_length=1000, null=True)),
                ('Home_Address', models.CharField(blank=True, max_length=1000, null=True)),
                ('Tax_Number', models.TextField(blank=True, null=True, unique=True)),
                ('Credit_limit', models.TextField(blank=True, null=True)),
                ('Reward_Point', models.TextField(blank=True, null=True)),
                ('Pay_Term', models.IntegerField(choices=[(0, 'Select'), (1, 'Daily'), (2, 'Weekly'), (3, 'Half of Month'), (4, 'Monthly'), (5, 'Half of Year'), (6, 'Yearly')], default=0)),
                ('Opening_Balance', models.TextField(blank=True, null=True)),
                ('Opening_Balance_Due', models.TextField(blank=True, null=True)),
                ('Advance_Balance', models.TextField(blank=True, null=True)),
                ('Total_Sale_Due', models.TextField(blank=True, null=True)),
                ('Total_Sell_Return_Due', models.TextField(blank=True, null=True)),
                ('Shipping_Address', models.CharField(blank=True, max_length=1000, null=True)),
                ('Created_At', models.DateTimeField(auto_now_add=True, null=True)),
                ('Business_Name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contact.business_name')),
                ('Contact_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contact.contact_id')),
                ('Customer_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contact.customer_group')),
            ],
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('p_k', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(blank=True, max_length=1000, null=True)),
                ('Email', models.EmailField(blank=True, max_length=1000, null=True, unique=True)),
                ('Address', models.CharField(blank=True, max_length=1000, null=True)),
                ('Mobile', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('Tax_Number', models.TextField(blank=True, null=True, unique=True)),
                ('Pay_Term', models.IntegerField(blank=True, choices=[(0, 'Select'), (1, 'Daily'), (2, 'Weekly'), (3, 'Half of Month'), (4, 'Monthly'), (5, 'Half of Year'), (6, 'Yearly')], default=0, null=True)),
                ('Opening_Balance_Due', models.TextField(blank=True, null=True)),
                ('Total_Amount', models.TextField(blank=True, null=True)),
                ('Advance_Amount', models.TextField(blank=True, null=True)),
                ('Due_Amount', models.TextField(blank=True, null=True)),
                ('Return_Due_Amount', models.TextField(blank=True, null=True)),
                ('Paid_Status', models.IntegerField(blank=True, choices=[(0, 'Checking'), (1, 'Payment Done'), (2, 'Due Running'), (3, 'Return Due Running')], default=0, null=True)),
                ('Created_At', models.DateTimeField(auto_now_add=True, null=True)),
                ('Business_Name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contact.business_name')),
                ('Contact_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contact.contact_id')),
                ('Supplier_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contact.customer_group')),
            ],
        ),
    ]
