# Generated by Django 5.0 on 2023-12-25 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contact', '0001_initial'),
        ('sell', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Due_Amount',
            fields=[
                ('p_k', models.AutoField(primary_key=True, serialize=False)),
                ('Due_amount', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expense_Categories_List',
            fields=[
                ('p_k', models.AutoField(primary_key=True, serialize=False)),
                ('Expense_Category_Name', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expense_Tax',
            fields=[
                ('p_k', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Invoice_No', models.CharField(blank=True, max_length=1000, null=True)),
                ('Tax_Number', models.TextField(blank=True, null=True)),
                ('Total_Amount', models.TextField(blank=True, null=True)),
                ('Payment_Method', models.CharField(blank=True, max_length=1000, null=True)),
                ('Vat', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('p_k', models.AutoField(primary_key=True, serialize=False)),
                ('Total_Purchase', models.TextField(blank=True, null=True)),
                ('Purchase_Including_Tax', models.TextField(blank=True, null=True)),
                ('Total_Purchase_Return_Including_Tax', models.TextField(blank=True, null=True)),
                ('Purchase_Deu', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sale_Purchase',
            fields=[
                ('p_k', models.AutoField(primary_key=True, serialize=False)),
                ('Sale_purchase', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('p_k', models.AutoField(primary_key=True, serialize=False)),
                ('Total_Sale', models.TextField(blank=True, null=True)),
                ('Sale_Including_Tax', models.TextField(blank=True, null=True)),
                ('Total_Sell_Return_Including_Tax', models.TextField(blank=True, null=True)),
                ('sale_Due', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Group_Report',
            fields=[
                ('p_k', models.AutoField(primary_key=True, serialize=False)),
                ('Total_Sale', models.TextField(blank=True, null=True)),
                ('Customer_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.customer_group')),
            ],
        ),
        migrations.CreateModel(
            name='Expense_Report',
            fields=[
                ('p_k', models.AutoField(primary_key=True, serialize=False)),
                ('Total_Expense', models.TextField(blank=True, null=True)),
                ('Expense_Categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detailed_report.expense_categories_list')),
            ],
        ),
        migrations.CreateModel(
            name='Input_Tax',
            fields=[
                ('p_k', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Reference_No', models.CharField(blank=True, max_length=1000, null=True)),
                ('Tax_Number', models.TextField(blank=True, null=True)),
                ('Total_Amount', models.TextField(blank=True, null=True)),
                ('Payment_Method', models.CharField(blank=True, max_length=1000, null=True)),
                ('Discount', models.TextField(blank=True, null=True)),
                ('Vat', models.TextField(blank=True, null=True)),
                ('Supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.business_name')),
            ],
        ),
        migrations.CreateModel(
            name='Item_Report',
            fields=[
                ('p_k', models.AutoField(primary_key=True, serialize=False)),
                ('Product', models.CharField(blank=True, max_length=1000, null=True)),
                ('SKU', models.CharField(blank=True, max_length=1000, null=True)),
                ('Description', models.CharField(blank=True, max_length=1000, null=True)),
                ('Purchase_Date', models.DateTimeField(auto_now_add=True)),
                ('Purchase', models.CharField(blank=True, max_length=1000, null=True)),
                ('Lot_Number', models.TextField(blank=True, null=True)),
                ('Purchase_Price', models.TextField(blank=True, null=True)),
                ('Sell_Date', models.DateTimeField(auto_now_add=True)),
                ('Sale', models.TextField(blank=True, null=True)),
                ('Sell_Quantity', models.TextField(blank=True, null=True)),
                ('Selling_Price', models.TextField(blank=True, null=True)),
                ('Subtotal', models.TextField(blank=True, null=True)),
                ('Customer', models.ForeignKey(db_column='customer', on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='contact.business_name')),
                ('Location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sell.location_set')),
                ('Supplier', models.ForeignKey(db_column='supplier', on_delete=django.db.models.deletion.CASCADE, related_name='supplier', to='contact.business_name')),
            ],
        ),
        migrations.CreateModel(
            name='Output_Tax',
            fields=[
                ('p_k', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Invoice_No', models.CharField(blank=True, max_length=1000, null=True)),
                ('Tax_Number', models.TextField(blank=True, null=True)),
                ('Total_Amount', models.TextField(blank=True, null=True)),
                ('Payment_Method', models.CharField(blank=True, max_length=1000, null=True)),
                ('Discount', models.TextField(blank=True, null=True)),
                ('Vat', models.TextField(blank=True, null=True)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.business_name')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Purchase_Report',
            fields=[
                ('p_k', models.AutoField(primary_key=True, serialize=False)),
                ('Product', models.CharField(blank=True, max_length=1000, null=True)),
                ('SKU', models.CharField(blank=True, max_length=1000, null=True)),
                ('Reference_No', models.CharField(blank=True, max_length=1000, null=True)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Quantity', models.TextField(blank=True, null=True)),
                ('Total_Unit_Adjusted', models.CharField(blank=True, max_length=1000, null=True)),
                ('Unit_Purchase_Price', models.TextField(blank=True, null=True)),
                ('Subtotal', models.TextField(blank=True, null=True)),
                ('Location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sell.location_set')),
                ('Supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.business_name')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Sell_Report',
            fields=[
                ('p_k', models.AutoField(primary_key=True, serialize=False)),
                ('Product', models.CharField(blank=True, max_length=1000, null=True)),
                ('SKU', models.CharField(blank=True, max_length=1000, null=True)),
                ('Invoice_No', models.TextField(blank=True, null=True)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Quantity', models.TextField(blank=True, null=True)),
                ('Unit_Price', models.TextField(blank=True, null=True)),
                ('Discount', models.TextField(blank=True, null=True)),
                ('Tax', models.TextField(blank=True, null=True)),
                ('Price_Inc_Tax', models.TextField(blank=True, null=True)),
                ('Total', models.TextField(blank=True, null=True)),
                ('Contact_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.contact_id')),
                ('Customer_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.business_name')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_Payment_Report',
            fields=[
                ('p_k', models.AutoField(primary_key=True, serialize=False)),
                ('Reference_No', models.CharField(blank=True, max_length=1000, null=True)),
                ('Paid_On', models.DateTimeField(auto_now_add=True)),
                ('Amount', models.TextField(blank=True, null=True)),
                ('Payment_Method', models.CharField(choices=[('None', 'None'), ('Cash', 'Cash'), ('Check', 'Check'), ('Bank-Card', 'Bank-Card'), ('Bkash', 'Bkash'), ('Nagad', 'Nagad'), ('Upay', 'Upay')], default='None', max_length=1000)),
                ('Purchase', models.CharField(blank=True, max_length=1000, null=True)),
                ('Supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.business_name')),
            ],
        ),
        migrations.CreateModel(
            name='Register_Report',
            fields=[
                ('p_k', models.AutoField(primary_key=True, serialize=False)),
                ('Open_Time', models.DateTimeField(auto_now_add=True)),
                ('Close_Time', models.DateTimeField(auto_now_add=True)),
                ('User', models.CharField(blank=True, max_length=1000, null=True)),
                ('Card_Slips', models.TextField(blank=True, null=True)),
                ('Total_Cheques', models.TextField(blank=True, null=True)),
                ('Total_Cash', models.TextField(blank=True, null=True)),
                ('Bank_Transfer', models.TextField(blank=True, null=True)),
                ('Advance_Payment', models.TextField(blank=True, null=True)),
                ('Bkash_Nagad_Rocket_Upay', models.TextField(blank=True, null=True)),
                ('Other_Payments', models.TextField(blank=True, null=True)),
                ('Total', models.TextField(blank=True, null=True)),
                ('Actions', models.CharField(choices=[('Action', 'Action'), ('Pay', 'Pay'), ('View', 'View'), ('Edit', 'Edit'), ('Delete', 'Delete'), ('Deactivate', 'Deactivate'), ('Ledger', 'Ledger'), ('Purchase', 'Purchase'), ('Stock Report', 'Stock Report'), ('Documents & Note', 'Documents & Note')], default='Action', max_length=1000)),
                ('Location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sell.location_set')),
            ],
        ),
        migrations.CreateModel(
            name='Sales_Report_Added',
            fields=[
                ('p_k', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Invoice_No', models.TextField(blank=True, null=True)),
                ('Payment_Status', models.CharField(choices=[('None', 'None'), ('Cash', 'Cash'), ('Check', 'Check'), ('Bank-Card', 'Bank-Card'), ('Bkash', 'Bkash'), ('Nagad', 'Nagad'), ('Upay', 'Upay')], default='None', max_length=1000)),
                ('Total_Amount', models.TextField(blank=True, null=True)),
                ('Total_Paid', models.TextField(blank=True, null=True)),
                ('Total_Remaining', models.TextField(blank=True, null=True)),
                ('Customer_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.business_name')),
                ('Location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sell.location_set')),
            ],
        ),
        migrations.CreateModel(
            name='Sales_Report_Expense',
            fields=[
                ('p_k', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Reference_No', models.TextField(blank=True, null=True)),
                ('Payment_Status', models.CharField(choices=[('None', 'None'), ('Cash', 'Cash'), ('Check', 'Check'), ('Bank-Card', 'Bank-Card'), ('Bkash', 'Bkash'), ('Nagad', 'Nagad'), ('Upay', 'Upay')], default='None', max_length=1000)),
                ('Total_Amount', models.TextField(blank=True, null=True)),
                ('Expense_For', models.TextField(blank=True, null=True)),
                ('Expense_Note', models.TextField(blank=True, null=True)),
                ('Expense_Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detailed_report.expense_categories_list')),
                ('Location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sell.location_set')),
            ],
        ),
        migrations.CreateModel(
            name='Sales_Report_With_Commission',
            fields=[
                ('p_k', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Invoice_No', models.TextField(blank=True, null=True)),
                ('Payment_Status', models.CharField(choices=[('None', 'None'), ('Cash', 'Cash'), ('Check', 'Check'), ('Bank-Card', 'Bank-Card'), ('Bkash', 'Bkash'), ('Nagad', 'Nagad'), ('Upay', 'Upay')], default='None', max_length=1000)),
                ('Total_Amount', models.TextField(blank=True, null=True)),
                ('Total_Paid', models.TextField(blank=True, null=True)),
                ('Total_Remaining', models.TextField(blank=True, null=True)),
                ('Customer_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.business_name')),
                ('Location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sell.location_set')),
            ],
        ),
        migrations.CreateModel(
            name='Sell_Payment_Report',
            fields=[
                ('p_k', models.AutoField(primary_key=True, serialize=False)),
                ('Reference_No', models.CharField(blank=True, max_length=1000, null=True)),
                ('Paid_On', models.DateTimeField(auto_now_add=True)),
                ('Amount', models.TextField(blank=True, null=True)),
                ('Payment_Method', models.CharField(choices=[('None', 'None'), ('Cash', 'Cash'), ('Check', 'Check'), ('Bank-Card', 'Bank-Card'), ('Bkash', 'Bkash'), ('Nagad', 'Nagad'), ('Upay', 'Upay')], default='None', max_length=1000)),
                ('Sell', models.CharField(blank=True, max_length=1000, null=True)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.business_name')),
                ('Customer_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.customer_group')),
            ],
        ),
        migrations.CreateModel(
            name='Stock_Adjustment_Report',
            fields=[
                ('p_k', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Reference_No', models.CharField(blank=True, max_length=1000, null=True)),
                ('Adjustment_Type', models.CharField(blank=True, max_length=1000, null=True)),
                ('Total_Amount', models.TextField(blank=True, null=True)),
                ('Total_Amount_Recovered', models.TextField(blank=True, max_length=1000, null=True)),
                ('Reason', models.CharField(blank=True, max_length=1000, null=True)),
                ('Added_By', models.CharField(blank=True, max_length=1000, null=True)),
                ('Location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sell.location_set')),
            ],
        ),
        migrations.CreateModel(
            name='Stock_Report',
            fields=[
                ('p_k', models.AutoField(primary_key=True, serialize=False)),
                ('SKU', models.CharField(blank=True, max_length=1000, null=True)),
                ('Product', models.CharField(blank=True, max_length=1000, null=True)),
                ('Variation', models.CharField(blank=True, max_length=1000, null=True)),
                ('Category', models.CharField(blank=True, max_length=1000, null=True)),
                ('Unit_Selling_Price', models.TextField(blank=True, null=True)),
                ('Current_Stock', models.TextField(blank=True, null=True)),
                ('Current_Stock_Value_by_purchase_price', models.TextField(blank=True, null=True)),
                ('Current_Stock_Value_by_sale_price', models.TextField(blank=True, null=True)),
                ('Location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sell.location_set')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier_And_Customer_Report',
            fields=[
                ('p_k', models.AutoField(primary_key=True, serialize=False)),
                ('Total_Purchase', models.TextField(blank=True, null=True)),
                ('Total_Purchase_Return', models.TextField(blank=True, null=True)),
                ('Total_Sale', models.TextField(blank=True, null=True)),
                ('Total_Sell_Return', models.TextField(blank=True, null=True)),
                ('Opening_Balance_Due', models.TextField(blank=True, null=True)),
                ('Due', models.TextField(blank=True, null=True)),
                ('Contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.business_name')),
            ],
        ),
    ]
