# Generated by Django 5.0 on 2023-12-25 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='All_Reports',
            fields=[
                ('p_k', models.AutoField(primary_key=True, serialize=False)),
                ('Total_Products_Item', models.TextField(blank=True, null=True)),
                ('Total_Purchase', models.TextField(blank=True, null=True)),
                ('Total_Sell_Return', models.TextField(blank=True, null=True)),
                ('Total_Customer_Due', models.TextField(blank=True, null=True)),
                ('Total_Supplier_Due', models.TextField(blank=True, null=True)),
                ('Total_Customer_Opening_Balance_Due', models.TextField(blank=True, null=True)),
                ('Total_Supplier_Opening_Balance_Due', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
