# Generated by Django 5.0 on 2023-12-25 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_location', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('reference_no', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('date', models.DateTimeField()),
                ('attached_document', models.FileField(blank=True, null=True, upload_to='expense_documents/')),
                ('applicable_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_refund', models.BooleanField(default=False)),
                ('expense_note', models.TextField(blank=True, null=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurring_interval', models.CharField(choices=[('Years', 'Years'), ('Months', 'Months'), ('Days', 'Days')], max_length=50)),
                ('recurring_interval_value', models.IntegerField(blank=True, null=True)),
                ('number_of_receipts', models.IntegerField(blank=True, null=True)),
                ('payment_due', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('due', 'Due'), ('partial', 'Partial')], default='due', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
                ('category_code', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField()),
                ('method', models.CharField(choices=[('card', 'Card'), ('cash', 'Cash'), ('cheque', 'Cheque'), ('bank_transfer', 'Bank Transfer')], max_length=50)),
                ('payment_account', models.CharField(blank=True, max_length=200, null=True)),
                ('card_number', models.CharField(blank=True, max_length=16, null=True)),
                ('card_holder_name', models.CharField(blank=True, max_length=200, null=True)),
                ('card_transaction_no', models.CharField(blank=True, max_length=100, null=True)),
                ('card_type', models.CharField(blank=True, choices=[('credit', 'Credit Card'), ('debit', 'Debit Card'), ('visa', 'Visa Card'), ('master', 'Master Card')], max_length=50, null=True)),
                ('card_expiry_month', models.IntegerField(blank=True, null=True)),
                ('card_expiry_year', models.IntegerField(blank=True, null=True)),
                ('card_security_code', models.CharField(blank=True, max_length=4, null=True)),
                ('cheque_no', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_account_no', models.CharField(blank=True, max_length=50, null=True)),
                ('other', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_note', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
