# Generated by Django 5.0 on 2023-12-25 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location_Set',
            fields=[
                ('p_k', models.AutoField(primary_key=True, serialize=False)),
                ('Location', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='List_Sell_Return',
            fields=[
                ('p_k', models.AutoField(primary_key=True, serialize=False)),
                ('Created_At', models.DateTimeField(auto_now_add=True)),
                ('Invoice_No', models.TextField(blank=True, null=True)),
                ('Parent_Sale', models.CharField(blank=True, max_length=1000, null=True)),
                ('Contact_Number', models.CharField(blank=True, max_length=20, null=True)),
                ('Payment_Status', models.CharField(choices=[('None', 'None'), ('Due', 'Due'), ('Partial', 'Partial'), ('Paid', 'Paid')], default='None', max_length=1000)),
                ('Total_Amount', models.TextField(blank=True, null=True)),
                ('Payment_Due', models.TextField(blank=True, null=True)),
                ('Customer_Name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contact.business_name')),
                ('Location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sell.location_set')),
            ],
        ),
        migrations.CreateModel(
            name='List_Draft',
            fields=[
                ('p_k', models.AutoField(primary_key=True, serialize=False)),
                ('Created_At', models.DateTimeField(auto_now_add=True)),
                ('Reference_No', models.TextField(blank=True, null=True)),
                ('Contact_Number', models.CharField(blank=True, max_length=20, null=True)),
                ('Total_Items', models.TextField(blank=True, null=True)),
                ('Added_By', models.CharField(blank=True, max_length=1000, null=True)),
                ('Customer_Name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contact.business_name')),
                ('Location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sell.location_set')),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('p_k', models.AutoField(primary_key=True, serialize=False)),
                ('Starts_At', models.CharField(blank=True, max_length=1000, null=True)),
                ('Ends_At', models.CharField(blank=True, max_length=1000, null=True)),
                ('Discount_Amount', models.TextField(blank=True, null=True)),
                ('Priority', models.CharField(blank=True, max_length=1000, null=True)),
                ('Brand', models.CharField(blank=True, max_length=1000, null=True)),
                ('Category', models.CharField(blank=True, max_length=1000, null=True)),
                ('Product', models.CharField(blank=True, max_length=1000, null=True)),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.business_name')),
                ('Location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sell.location_set')),
            ],
        ),
        migrations.CreateModel(
            name='All_Sales',
            fields=[
                ('p_k', models.AutoField(primary_key=True, serialize=False)),
                ('Created_At', models.DateTimeField(auto_now_add=True)),
                ('Invoice_No', models.TextField(blank=True, null=True)),
                ('Contact_Number', models.CharField(blank=True, max_length=20, null=True)),
                ('Payment_Status', models.CharField(choices=[('None', 'None'), ('Due', 'Due'), ('Partial', 'Partial'), ('Paid', 'Paid')], default='None', max_length=1000)),
                ('Payment_Method', models.CharField(choices=[('None', 'None'), ('Cash', 'Cash'), ('Check', 'Check'), ('Bank-Card', 'Bank-Card'), ('Bkash', 'Bkash'), ('Nagad', 'Nagad'), ('Upay', 'Upay')], default='None', max_length=1000)),
                ('Total_Amount', models.TextField(blank=True, null=True)),
                ('Total_Paid', models.TextField(blank=True, null=True)),
                ('Sell_Due', models.TextField(blank=True, null=True)),
                ('Sell_Return_Due', models.TextField(blank=True, null=True)),
                ('Shipping_Status', models.CharField(blank=True, max_length=1000, null=True)),
                ('Shipping_Address', models.CharField(blank=True, max_length=1000, null=True)),
                ('Total_Items', models.TextField(blank=True, null=True)),
                ('Added_By', models.CharField(blank=True, max_length=1000, null=True)),
                ('Customer_Name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contact.business_name')),
                ('Location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sell.location_set')),
            ],
        ),
        migrations.CreateModel(
            name='Shipments',
            fields=[
                ('p_k', models.AutoField(primary_key=True, serialize=False)),
                ('Created_At', models.DateTimeField(auto_now_add=True)),
                ('Invoice_No', models.TextField(blank=True, null=True)),
                ('Contact_Number', models.CharField(blank=True, max_length=20, null=True)),
                ('Shipping_Status', models.CharField(choices=[('None', 'None'), ('Ordered', 'Ordered'), ('Pending', 'Pending')], default='None', max_length=1000)),
                ('Payment_Status', models.CharField(choices=[('None', 'None'), ('Due', 'Due'), ('Partial', 'Partial'), ('Paid', 'Paid')], default='None', max_length=1000)),
                ('Service_Staff', models.CharField(blank=True, max_length=1000, null=True)),
                ('Customer_Name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contact.business_name')),
                ('Location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sell.location_set')),
            ],
        ),
    ]
