# Generated by Django 5.0 on 2023-12-27 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
        ('sell', '0001_initial'),
        ('user_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Payment_Status', models.CharField(choices=[('None', 'None'), ('Due', 'Due'), ('Partial', 'Partial'), ('Paid', 'Paid')], default='None', max_length=1000)),
                ('Date_Range', models.CharField(blank=True, max_length=1000, null=True)),
                ('Shipping_Status', models.CharField(choices=[('None', 'None'), ('Ordered', 'Ordered'), ('Pending', 'Pending')], default='None', max_length=1000)),
                ('Business_Location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sell.location_set')),
                ('Customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contact.customers')),
                ('Sales_Commission_Agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_management.sales_commission_ager')),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
