# Generated by Django 5.0 on 2023-12-17 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sell', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock_Adjustment',
            fields=[
                ('p_k', models.AutoField(primary_key=True, serialize=False)),
                ('Action', models.IntegerField(blank=True, choices=[(0, 'None'), (1, 'View'), (2, 'Delete')], default=0, null=True)),
                ('Date', models.DateTimeField(auto_now_add=True, null=True)),
                ('Reference_No', models.CharField(blank=True, max_length=1000, null=True)),
                ('Adjustment_Type', models.CharField(blank=True, max_length=1000, null=True)),
                ('Total_Amount', models.TextField(blank=True, null=True)),
                ('Total_Amount_Recovered', models.TextField(blank=True, null=True)),
                ('Reason', models.CharField(blank=True, max_length=1000, null=True)),
                ('Added_By', models.CharField(blank=True, max_length=1000, null=True)),
                ('Location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sell.location_set')),
            ],
        ),
    ]
