# Generated by Django 5.0 on 2023-12-25 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='All_Customer_Number',
            fields=[
                ('p_k', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='All_Number',
            fields=[
                ('p_k', models.AutoField(primary_key=True, serialize=False)),
                ('Number', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='All_Supplier_Number',
            fields=[
                ('p_k', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='All_Customer_Number_Smss',
            fields=[
                ('p_k', models.AutoField(primary_key=True, serialize=False)),
                ('sms', models.TextField(blank=True, null=True)),
                ('numbers', models.ManyToManyField(to='smss.all_customer_number')),
            ],
        ),
        migrations.CreateModel(
            name='All_Number_Sms',
            fields=[
                ('p_k', models.AutoField(primary_key=True, serialize=False)),
                ('sms', models.TextField(blank=True, null=True)),
                ('numbers', models.ManyToManyField(to='smss.all_number')),
            ],
        ),
        migrations.CreateModel(
            name='All_Supplier_Number_Smss',
            fields=[
                ('p_k', models.AutoField(primary_key=True, serialize=False)),
                ('sms', models.TextField(blank=True, null=True)),
                ('numbers', models.ManyToManyField(to='smss.all_supplier_number')),
            ],
        ),
    ]
